package co.edu.sena.actividadanimales.app;

import co.edu.sena.actividadanimales.invertebrados.AbejaHembra;
import co.edu.sena.actividadanimales.invertebrados.AbejaMacho;
import co.edu.sena.actividadanimales.invertebrados.AraniaHembra;
import co.edu.sena.actividadanimales.invertebrados.AraniaMacho;
import co.edu.sena.actividadanimales.invertebrados.CalamarHembra;
import co.edu.sena.actividadanimales.invertebrados.CalamarMacho;
import co.edu.sena.actividadanimales.invertebrados.CangrejoHembra;
import co.edu.sena.actividadanimales.invertebrados.CangrejoMacho;
import co.edu.sena.actividadanimales.invertebrados.CaracolHembra;
import co.edu.sena.actividadanimales.invertebrados.CaracolMacho;
import co.edu.sena.actividadanimales.invertebrados.CienpiesHembra;
import co.edu.sena.actividadanimales.invertebrados.CienpiesMacho;
import co.edu.sena.actividadanimales.invertebrados.ErizoDeMarHembra;
import co.edu.sena.actividadanimales.invertebrados.ErizoDeMarMacho;
import co.edu.sena.actividadanimales.invertebrados.EscorpionHembra;
import co.edu.sena.actividadanimales.invertebrados.EscorpionMacho;
import co.edu.sena.actividadanimales.invertebrados.Esponjas;
import co.edu.sena.actividadanimales.invertebrados.EstrellaDeMar;
import co.edu.sena.actividadanimales.invertebrados.HormigaHembra;
import co.edu.sena.actividadanimales.invertebrados.HormigaMacho;
import co.edu.sena.actividadanimales.invertebrados.LangostaHembra;
import co.edu.sena.actividadanimales.invertebrados.LangostaMacho;
import co.edu.sena.actividadanimales.invertebrados.LiebreDeMarHembra;
import co.edu.sena.actividadanimales.invertebrados.LiebreDeMarMacho;
import co.edu.sena.actividadanimales.invertebrados.LombrizDeTierraHembra;
import co.edu.sena.actividadanimales.invertebrados.LombrizDeTierraMacho;
import co.edu.sena.actividadanimales.invertebrados.MedusaHembra;
import co.edu.sena.actividadanimales.invertebrados.MedusaMacho;
import co.edu.sena.actividadanimales.invertebrados.MejillonHembra;
import co.edu.sena.actividadanimales.invertebrados.MejillonMacho;
import co.edu.sena.actividadanimales.invertebrados.MilpiesHembra;
import co.edu.sena.actividadanimales.invertebrados.MilpiesMacho;
import co.edu.sena.actividadanimales.invertebrados.OstraHembra;
import co.edu.sena.actividadanimales.invertebrados.OstraMacho;
import co.edu.sena.actividadanimales.invertebrados.Polipos;
import co.edu.sena.actividadanimales.invertebrados.PulpoHembra;
import co.edu.sena.actividadanimales.invertebrados.PulpoMacho;
import co.edu.sena.actividadanimales.invertebrados.SanguijuelaHembra;
import co.edu.sena.actividadanimales.invertebrados.SanguijuelaMacho;
import co.edu.sena.actividadanimales.vertebrados.AguilaHembra;
import co.edu.sena.actividadanimales.vertebrados.AguilaMacho;
import co.edu.sena.actividadanimales.vertebrados.AtunHembra;
import co.edu.sena.actividadanimales.vertebrados.AtunMacho;
import co.edu.sena.actividadanimales.vertebrados.AvestruzHembra;
import co.edu.sena.actividadanimales.vertebrados.AvestruzMacho;
import co.edu.sena.actividadanimales.vertebrados.CocodriloHembra;
import co.edu.sena.actividadanimales.vertebrados.CocodriloMacho;
import co.edu.sena.actividadanimales.vertebrados.Hombre;
import co.edu.sena.actividadanimales.vertebrados.Mujer;
import co.edu.sena.actividadanimales.vertebrados.OrnitorrincoHembra;
import co.edu.sena.actividadanimales.vertebrados.OrnitorrincoMacho;
import co.edu.sena.actividadanimales.vertebrados.PerroHembra;
import co.edu.sena.actividadanimales.vertebrados.PerroMacho;
import co.edu.sena.actividadanimales.vertebrados.SalamandraHembra;
import co.edu.sena.actividadanimales.vertebrados.SalamandraMacho;
import co.edu.sena.actividadanimales.vertebrados.SapoHembra;
import co.edu.sena.actividadanimales.vertebrados.SapoMacho;
import co.edu.sena.actividadanimales.vertebrados.TiburonHembra;
import co.edu.sena.actividadanimales.vertebrados.TiburonMacho;
import co.edu.sena.actividadanimales.vertebrados.TortugaHembra;
import co.edu.sena.actividadanimales.vertebrados.TortugaMacho;

public class AnimalesApp {
	public static void main(String[] args) {
		TortugaHembra t1 = new TortugaHembra();
		t1.comer();
		TortugaMacho t2 = new TortugaMacho();
		t2.comer();
		CocodriloHembra c1 = new CocodriloHembra();
		c1.comer();
		CocodriloMacho c2 = new CocodriloMacho();
		c2.comer();
		TiburonHembra t3 = new TiburonHembra();
		t3.comer();
		TiburonMacho t4 = new TiburonMacho();
		t4.comer();
		AtunHembra a1 = new AtunHembra();
		a1.comer();
		AtunMacho a2 = new AtunMacho();
		a2.comer();
		PerroHembra p1 = new PerroHembra();
		p1.comer();
		PerroMacho p2 = new PerroMacho();
		p2.comer();
		OrnitorrincoHembra o1 = new OrnitorrincoHembra();
		o1.comer();
		OrnitorrincoMacho o2 = new OrnitorrincoMacho();
		o2.comer();
		Hombre h1 = new Hombre();
		h1.comer();
		Mujer m1 = new Mujer();
		m1.comer();
		AvestruzHembra a3 = new AvestruzHembra();
		a3.comer();
		AvestruzMacho a4 = new AvestruzMacho();
		a4.comer();
		AguilaHembra ag1 = new AguilaHembra();
		ag1.comer();
		AguilaMacho ag2 = new AguilaMacho();
		ag2.comer();
		SalamandraHembra s1 = new SalamandraHembra();
		s1.comer();
		SalamandraMacho s2 = new SalamandraMacho();
		s2.comer();
		SapoHembra s3 = new SapoHembra();
		s3.comer();
		SapoMacho s4 = new SapoMacho();
		s4.comer();
		AraniaHembra ar1 = new AraniaHembra();
		ar1.comer();
		AraniaMacho ar2 = new AraniaMacho();
		ar2.comer();
		EscorpionHembra es1 = new EscorpionHembra();
		es1.comer();
		EscorpionMacho es2 = new EscorpionMacho();
		es2.comer();
		CangrejoHembra ca1 = new CangrejoHembra();
		ca1.comer();
		CangrejoMacho ca2 = new CangrejoMacho();
		ca2.comer();
		LangostaHembra l1 = new LangostaHembra();
		l1.comer();
		LangostaMacho l2 = new LangostaMacho();
		l2.comer();
		AbejaHembra ab1 = new AbejaHembra();
		ab1.comer();
		AbejaMacho ab2 = new AbejaMacho();
		ab2.comer();
		HormigaHembra ho1 = new HormigaHembra();
		ho1.comer();
		HormigaMacho ho2 = new HormigaMacho();
		ho2.comer();
		CienpiesHembra ci1 = new CienpiesHembra();
		ci1.comer();
		CienpiesMacho ci2 = new CienpiesMacho();
		ci2.comer();
		MilpiesHembra mi1 = new MilpiesHembra();
		mi1.comer();
		MilpiesMacho mi2 = new MilpiesMacho();
		mi2.comer();
		ErizoDeMarHembra er1 = new ErizoDeMarHembra();
		er1.comer();
		ErizoDeMarMacho er2 = new ErizoDeMarMacho();
		er2.comer();
		EstrellaDeMar est = new EstrellaDeMar();
		est.comer();
		MejillonHembra me1 = new MejillonHembra();
		me1.comer();
		MejillonMacho me2 = new MejillonMacho();
		me2.comer();
		OstraHembra os1 = new OstraHembra();
		os1.comer();
		OstraMacho os2 = new OstraMacho();
		os2.comer();
		CalamarMacho cal1 = new CalamarMacho();
		cal1.comer();
		CalamarHembra cal2 = new CalamarHembra();
		cal2.comer();
		PulpoHembra pu1 = new PulpoHembra();
		pu1.comer();
		PulpoMacho pu2 = new PulpoMacho();
		pu2.comer();
		CaracolHembra car1 = new CaracolHembra();
		car1.comer();
		CaracolMacho car2 = new CaracolMacho();
		car2.comer();
		LiebreDeMarHembra li1 = new LiebreDeMarHembra();
		li1.comer();
		LiebreDeMarMacho li2 = new LiebreDeMarMacho();
		li2.comer();
		MedusaHembra med1 = new MedusaHembra();
		med1.comer();
		MedusaMacho med2 = new MedusaMacho();
		med2.comer();
		Polipos pol = new Polipos();
		pol.comer();
		LombrizDeTierraHembra lom1 = new LombrizDeTierraHembra();
		lom1.comer();
		LombrizDeTierraMacho lom2 = new LombrizDeTierraMacho();
		lom2.comer();
		SanguijuelaHembra san1 = new SanguijuelaHembra();
		san1.comer();
		SanguijuelaMacho san2 = new SanguijuelaMacho();
		san2.comer();
		Esponjas esp = new Esponjas();
		esp.comer();
	}

}
